name: bios admin UI multi arch build 

on:
  workflow_dispatch:
    inputs:
      alpine_version:
        description: 'alpine version'
        required: true
        type: string
        default: '3.20'
      pyfina:
        description: 'pyfina version'
        required: true
        type: string
        default: '0.0.6'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        id: get_date
        name: get current date
        run: |
          today=$(date +'%Y-%m-%d')
          echo $today
          echo "today=$today" >> "$GITHUB_OUTPUT"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: admin/.
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            "BUILD_FROM=alpine:${{ inputs.alpine_version }}"
            "PYFINA_VERSION=${{ inputs.pyfina }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/admin:${{ inputs.alpine_version }}_${{ steps.get_date.outputs.today }}
