name: themis docker images to docker hub

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - alpine_version: 3.16
          php_version: 8
          use_redispy_apk: 0
        - alpine_version: 3.18
          php_version: 81
          use_redispy_apk: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: emoncms/alpine_persistent/.
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            "EMONCMS_SRC=https://github.com/alexandrecuer/emoncms"
            "BUILD_FROM=alpine:${{ matrix.alpine_version }}"
            "PHP_VER=${{ matrix.php_version }}"
            "PHP_CONF=/etc/php${{ matrix.php_version }}/conf.d"
            "USE_REDISPY_APK=${{ matrix.use_redispy_apk }}"
          push: true
          tags: alexjunk/themis:alpine${{ matrix.alpine_version }}
