name: code server container

on:
  workflow_dispatch:
    inputs:
      base_container:
        description: 'tf_multiarch version'
        required: true
        type: string
        default: 'ubuntu22.04_numpy1.26.4_tflite2.13.0_paho2.1.0_pymodbus3.6.8'
      code_version:
        description: 'code server version'
        required: true
        type: string
        default: '4.98.2'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        id: tag
        name: create tag
        run: |
          t0=${{ inputs.code_version }}
          t1=_${{ inputs.base_container }}
          echo $t0
          echo $t1
          echo "tag=$t0$t1" >> "$GITHUB_OUTPUT"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: code/.
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            "BUILD_FROM=alexjunk/tf_multiarch:${{ inputs.base_container }}"
            "VERSION=${{ inputs.code_version }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code:${{ steps.tag.outputs.tag }}
