name: emonhub with version

on:
  workflow_dispatch:
    alpine:
      description: 'alpine version'
      required: true
      type: string
      default: '3.20'
    paho:
      description: 'paho mqtt version'
      required: true
      type: string
      default: '1.6.1'
    pymodbus:
      description: 'pymodbus version'
      required: true
      type: string
      default: '3.6.8'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      src: openenergymonitor/emonhub
      branch: stable
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        id: tag
        name: create tag
        run: |
          wget https://raw.githubusercontent.com/${{ env.src }}/${{ env.branch }}/module.json
          version=$(cat module.json | jq --raw-output '.version')
          t0=$version
          t1=_alpine${{ inputs.alpine }}
          t2=_paho${{ inputs.paho }}
          t3=_pymodbus${{ inputs.pymodbus }}
          echo "tag=$t0$t1$t2$t3" >> "$GITHUB_OUTPUT"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: emonhub/.
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            "SRC=https://github.com/${{ env.src }}"
            "BRANCH=${{ env.branch }}"
            "BUILD_FROM=alpine:${{ inputs.alpine }}"
            "PYMODBUS_VERSION=${{ inputs.pymodbus }}"
            "PAHO_VERSION=${{ inputs.paho }}"
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/emonhub:${{ steps.tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/emonhub:latest
