name: a matrix test

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - alpine_version: 3.16
          php_version: 8
        - alpine_version: 3.18
          php_version: 81
    steps:
      - name: testing...
        run: |
          echo ${{ matrix.php_version }}
          echo ${{ matrix.alpine_version}}
