name: a matrix test

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emoncms_version: ["11.4.2"]
        include:
        - alpine_version: 3.16
          php_version: 8
        - alpine_version: 3.18
          php_version: 81
    steps:
      - name: testing...
        run: |
          echo "$matrix.emoncms_version"
          echo "$php_version $matrix.alpine_version"
