name: a matrix test

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emoncms_version: [11.4.2]
        alpine_version: [3.16, 3.18]
        php_version: [8, 81]
        exclude:
        - alpine_version: 3.16
          php_version: 81
        - alpine_version: 3.18
          php_version: 8
    steps:
      - name: fetching version number
        run: |
          wget https://raw.githubusercontent.com/emoncms/emoncms/master/version.json
          master_version=$(cat version.json | jq '.version')
          echo $master_version
          echo "master_version=$master_version" >> "$GITHUB_ENV"
      - name: using..
        run: |
          echo $master_version
          echo ${{ matrix.emoncms_version }}
          echo ${{ matrix.php_version }}
          echo ${{ matrix.alpine_version}}
