name: a matrix test

on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      something: a_simple_test 
    strategy:
      matrix:
        emoncms_version: [11.4.2]
        alpine_version: [3.16, 3.18]
        php_version: [8, 81]
        use_redispy_apk: [0, 1]
        exclude:
        - alpine_version: 3.16
          php_version: 81
        - alpine_version: 3.18
          php_version: 8
        - alpine_version: 3.16
          use_redispy_apk: 1
        - alpine_version: 3.18
          use_redispy_apk: 0
    steps:
      - name: fetching version number
        run: |
          wget https://raw.githubusercontent.com/emoncms/emoncms/master/version.json
          master_version=$(cat version.json | jq --raw-output '.version')
          echo $master_version
          echo "master_version=$master_version" >> "$GITHUB_ENV"
      -
        id: tag
        name: create tag
        run: |
          tag=alpine${{ matrix.alpine_version }}
          tag1=$tag${{ '_version' }}$master_version
          echo "tag=$tag1" >> "$GITHUB_ENV"
      - name: using..
        run: |
          echo ${{ env.something }}
          echo $master_version
          echo $tag
          echo ${{ matrix.emoncms_version }}
          echo ${{ matrix.php_version }}
          echo ${{ matrix.alpine_version}}
          echo ${{ matrix.use_redispy_apk }}
