name: multi arch amd/arm 64 build of tflite with pip

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: 
          - 20.04
          - 22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: tf/.
          platforms: linux/amd64,linux/arm64
          build-args: BUILD_FROM=ubuntu:${{ matrix.ubuntu_version }}
          push: true
          tags: alexjunk/tf:ubuntu${{ matrix.ubuntu_version }}
