name: tflite amd/arm64 build with versions

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [22.04]
        tflite: [2.13.0]
        numpy: [1.26.4]
        paho: [1.6.1, 2.1.0]
        pymodbus: [3.4.1, 3.6.8]
        exclude:
          - paho: 1.6.1
            pymodbus: 3.6.8
          - paho: 2.1.0
            pymodbus: 3.4.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        id: tag
        name: create tag
        run: |
          t0=ubuntu${{ matrix.ubuntu_version }}
          t1=_numpy${{ matrix.numpy }}
          t2=_tflite${{ matrix.tflite }}
          t3=_paho${{ matrix.paho }}
          t4=_pymodbus${{ matrix.pymodbus}}
          echo $t0
          echo $t1
          echo "tag=$t0$t1$t2$t3$t4" >> "$GITHUB_OUTPUT"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: tf/.
          platforms: linux/amd64,linux/arm64
          build-args: |
            "BUILD_FROM=ubuntu:${{ matrix.ubuntu_version }}"
            "PYMODBUS_VERSION=${{ matrix.pymodbus}}"
            "PAHO_VERSION=${{ matrix.paho }}"
            "NUMPY_VERSION=${{ matrix.numpy }}"
            "TFLITE_VERSION=${{ matrix.tflite }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tf:${{ steps.tag.outputs.tag }}
