name: multi arch amd/arm 64 build of tflite with pip with versions in tag

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: 
          - 22.04
        tflite:
          - 2.13.0
        paho:
          - 2.1.0
        pymodbus:
          - 3.6.8
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: tf/.
          platforms: linux/amd64,linux/arm64
          build-args: |
            "BUILD_FROM=ubuntu:${{ matrix.ubuntu_version }}"
            "PYMODBUS_VERSION=${{ matrix.pymodbus}}"
            "PAHO_VERSION=${{ matrix.paho }}"
            "TFLITE_VERSION=${{ matrix.tflite }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tf:ubuntu${{ matrix.ubuntu_version }}_tflite${{ matrix.tflite }}_paho${{ matrix.paho }}_pymodbus${{ matrix.pymodbus}}
